# Generated by Django 6.0 on 2026-06-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
