# Generated by Django 6.0 on 2026-07-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
